BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "pokemon" (
	"poke_id"	INTEGER,
	"name_id"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("poke_id")
);
CREATE TABLE IF NOT EXISTS "stats" (
	"poke_id"	INTEGER,
	"hp"	INTEGER NOT NULL,
	"attack"	INTEGER NOT NULL,
	"defense"	INTEGER NOT NULL,
	"spAttack"	INTEGER NOT NULL,
	"spDefense"	INTEGER NOT NULL,
	"speed"	INTEGER NOT NULL,
	PRIMARY KEY("poke_id"),
	FOREIGN KEY("poke_id") REFERENCES "pokemon"("poke_id") ON UPDATE CASCADE ON DELETE CASCADE ON UPDATE RESTRICT ON DELETE RESTRICT
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS "lineage" (
	"poke_id"	INTEGER,
	"firstborn_id"	INTEGER NOT NULL,
	"quantity"	INTEGER NOT NULL,
	"phase"	INTEGER NOT NULL,
	PRIMARY KEY("poke_id"),
	FOREIGN KEY("poke_id") REFERENCES "pokemon"("poke_id") ON UPDATE CASCADE ON DELETE CASCADE ON UPDATE RESTRICT ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "poke_type" (
	"poke_id"	INTEGER,
	"type1_id"	INTEGER(2) NOT NULL,
	"type2_id"	INTEGER(2) NOT NULL,
	PRIMARY KEY("poke_id"),
	FOREIGN KEY("poke_id") REFERENCES "pokemon"("poke_id") ON UPDATE CASCADE ON DELETE CASCADE ON UPDATE RESTRICT ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "measure" (
	"poke_id"	INTEGER,
	"height"	REAL NOT NULL,
	"weight"	REAL NOT NULL,
	"legendary"	INTEGER NOT NULL,
	PRIMARY KEY("poke_id"),
	FOREIGN KEY("poke_id") REFERENCES "pokemon"("poke_id") ON UPDATE CASCADE ON DELETE CASCADE ON UPDATE RESTRICT ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "dataquerytime" (
	"user_id"	INTEGER,
	"query_date"	TEXT NOT NULL UNIQUE,
	"query_hour"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("user_id")
);
COMMIT;
